import type { EventCategory, EventsData, EventStat } from "./types";

export const eventCategories: EventCategory[] = [
  { id: "ongoing", name: "Ongoing Events", count: 1, icon: "⏳" },
  { id: "past", name: "Past Events", count: 6, icon: "✅" },
  { id: "future", name: "Future Events", count: 7, icon: "📅" },
];

export const eventsData: EventsData = {
  ongoing: [
    {
      id: 1,
      title: "2nd International General Science Olympiad",
      shortTitle: "2nd IGSO",
      date: "Ongoing",
      location: "Various Locations Nationwide",
      description:
        "A prestigious international science competition challenging young minds with innovative problem-solving and critical thinking tasks.",
      image: "/events/igso-banner.jpg",
      buttonText: "Learn More & Register",
      buttonLink: "https://sciencebaze.com/direct-reg/second-igso",
      status: "ongoing",
      category: "Olympiad",
      participants: "5,000+",
      isFeatured: true,
      highlights: [
        "International recognition",
        "Multiple difficulty levels",
        "Online & offline rounds",
      ],
    },
  ],

  past: [
    {
      id: 1,
      title: "1st National General Science Olympiad",
      shortTitle: "1st NGSO",
      date: "Completed • 2023",
      location: "National Level",
      description:
        "The inaugural national science competition that brought together talented students from across the country.",
      image: "/events/1st-ngso.jpg",
      buttonText: "View Gallery",
      buttonLink:
        "https://drive.google.com/drive/folders/1tDzz4d2E5BrUbFO3ZE2-u9fn3wcVB8Ei?usp=sharing",
      galleryLink:
        "https://drive.google.com/drive/folders/1tDzz4d2E5BrUbFO3ZE2-u9fn3wcVB8Ei?usp=sharing",
      status: "completed",
      category: "Olympiad",
      participants: "2,500+",
      highlights: ["National level", "500+ schools", "Award ceremony"],
    },
    {
      id: 2,
      title: "2nd IGSO - Chandpur District Round",
      shortTitle: "2nd IGSO Chandpur",
      date: "Completed • January 2024",
      location: "Chandpur, Bangladesh",
      description:
        "District level competition showcasing exceptional talent from Chandpur region.",
      image: "/events/chandpur-round.jpg",
      buttonText: "View Photos",
      buttonLink:
        "https://drive.google.com/drive/folders/1y7ctvV5HlHOeN8TesBQrKnqItu2kQpIV?usp=sharing",
      galleryLink:
        "https://drive.google.com/drive/folders/1y7ctvV5HlHOeN8TesBQrKnqItu2kQpIV?usp=sharing",
      status: "completed",
      category: "District Round",
      participants: "400+",
      highlights: ["400+ participants", "20 schools", "District champions"],
    },
    {
      id: 3,
      title: "2nd IGSO - Barguna District Round",
      shortTitle: "2nd IGSO Barguna",
      date: "Completed • February 2024",
      location: "Barguna, Bangladesh",
      description:
        "Exciting district competition held in Barguna with enthusiastic participation.",
      image: "/events/barguna-round.jpg",
      buttonText: "View Highlights",
      buttonLink: "#",
      status: "completed",
      category: "District Round",
      participants: "350+",
      highlights: [
        "Coastal region",
        "New partnerships",
        "Community engagement",
      ],
    },
    // {
    //   id: 4,
    //   title: "2nd IGSO - Patuakhali District Round",
    //   shortTitle: "2nd IGSO Patuakhali",
    //   date: "Completed • February 2024",
    //   location: "Patuakhali, Bangladesh",
    //   description:
    //     "District level competition in Patuakhali fostering scientific curiosity.",
    //   image: "/events/patuakhali-round.jpg",
    //   buttonText: "View Event Details",
    //   buttonLink: "#",
    //   status: "completed",
    //   category: "District Round",
    //   participants: "420+",
    //   highlights: [
    //     "420+ students",
    //     "Practical experiments",
    //     "Local media coverage",
    //   ],
    // },
    // {
    //   id: 5,
    //   title: "2nd IGSO - Imperial International School Campus Round",
    //   shortTitle: "2nd IGSO Imperial School",
    //   date: "Completed • March 2024",
    //   location: "Dhaka, Bangladesh",
    //   description: "Campus level competition at Imperial International School.",
    //   image: "/events/imperial-school.jpg",
    //   buttonText: "View Campus Round",
    //   buttonLink: "#",
    //   status: "completed",
    //   category: "Campus Round",
    //   participants: "280+",
    //   highlights: ["Elite school", "Advanced labs", "International curriculum"],
    // },
    // {
    //   id: 6,
    //   title: "Science Discussion Season 1 - Episode 1",
    //   shortTitle: "Science Discussion S1E1",
    //   date: "Completed • December 2023",
    //   location: "Online Session",
    //   description:
    //     "First episode of our science discussion series featuring expert talks and interactive Q&A.",
    //   image: "/events/science-discussion.jpg",
    //   buttonText: "Watch Recording",
    //   buttonLink:
    //     "https://drive.google.com/file/d/1q9QIrQGLCDwIKnvCogNz5l3dLEomlBh3/view?usp=sharing",
    //   videoLink:
    //     "https://drive.google.com/file/d/1q9QIrQGLCDwIKnvCogNz5l3dLEomlBh3/view?usp=sharing",
    //   status: "completed",
    //   category: "Discussion Series",
    //   participants: "1,200+",
    //   highlights: ["Expert panel", "Live Q&A", "Recorded session available"],
    // },
  ],

  future: [
    {
      id: 1,
      title: "Science Discussion Season 2 - Episode 1",
      shortTitle: "Science Discussion S2E1",
      date: "Coming Soon • June 2024",
      location: "Online Session",
      description:
        "The awaited return of our science discussion series with new topics and expert panelists.",
      image: "/events/science-discussion-s2.jpg",
      buttonText: "Get Notified",
      buttonLink: "#",
      status: "upcoming",
      category: "Discussion Series",
      participants: "Expected: 2,000+",
      registrationOpen: true,
      highlights: [
        "New topics",
        "Interactive sessions",
        "Certificate of participation",
      ],
    },
    {
      id: 2,
      title: "2nd IGSO - Jessore District Round",
      shortTitle: "2nd IGSO Jessore",
      date: "Upcoming • July 2024",
      location: "Jessore, Bangladesh",
      description:
        "District level competition coming to Jessore. Registration open for schools.",
      image: "/events/jessore-upcoming.jpg",
      buttonText: "Register Now",
      buttonLink: "#",
      status: "upcoming",
      category: "District Round",
      participants: "Expected: 500+",
      registrationOpen: true,
      highlights: ["New region", "School partnerships", "Special workshops"],
    },
    {
      id: 3,
      title: "2nd IGSO - Tangail District Round",
      shortTitle: "2nd IGSO Tangail",
      date: "Upcoming • August 2024",
      location: "Tangail, Bangladesh",
      description: "Exciting science competition coming to Tangail district.",
      image: "/events/tangail-upcoming.jpg",
      buttonText: "Express Interest",
      buttonLink: "#",
      status: "upcoming",
      category: "District Round",
      participants: "Expected: 450+",
      highlights: [
        "Textile region focus",
        "Industry collaboration",
        "Practical science",
      ],
    },
    // {

    //   id: 4,
    //   title: "2nd IGSO - Sylhet District Round",
    //   shortTitle: "2nd IGSO Sylhet",
    //   date: "Upcoming • September 2024",
    //   location: "Sylhet, Bangladesh",
    //   description:
    //     "District round of the prestigious science olympiad in Sylhet region.",
    //   image: "/events/sylhet-upcoming.jpg",
    //   buttonText: "Learn More",
    //   buttonLink: "#",
    //   status: "upcoming",
    //   category: "District Round",
    //   participants: "Expected: 600+",
    //   highlights: [
    //     "Tea garden region",
    //     "Environmental focus",
    //     "Cultural integration",
    //   ],
    // },
    // {
    //   id: 5,
    //   title: "2nd IGSO - Gazipur (BOF) District Round",
    //   shortTitle: "2nd IGSO Gazipur",
    //   date: "Upcoming • October 2024",
    //   location: "Gazipur, Bangladesh",
    //   description:
    //     "Science competition at Gazipur BOF campus. Open for all schools in the region.",
    //   image: "/events/gazipur-upcoming.jpg",
    //   buttonText: "Check Eligibility",
    //   buttonLink: "#",
    //   status: "upcoming",
    //   category: "District Round",
    //   participants: "Expected: 550+",
    //   highlights: ["Industrial zone", "Technical focus", "Industry experts"],
    // },
    // {
    //   id: 6,
    //   title: "2nd IGSO - Jhenaidah District Round",
    //   shortTitle: "2nd IGSO Jhenaidah",
    //   date: "Upcoming • November 2024",
    //   location: "Jhenaidah, Bangladesh",
    //   description:
    //     "Bringing the science olympiad to Jhenaidah district students.",
    //   image: "/events/jhenaidah-upcoming.jpg",
    //   buttonText: "View Schedule",
    //   buttonLink: "#",
    //   status: "upcoming",
    //   category: "District Round",
    //   participants: "Expected: 400+",
    //   highlights: ["Agricultural focus", "Local schools", "Community support"],
    // },
    // {
    //   id: 7,
    //   title: "2nd IGSO - Noakhali District Round",
    //   shortTitle: "2nd IGSO Noakhali",
    //   date: "Upcoming • December 2024",
    //   location: "Noakhali, Bangladesh",
    //   description: "Final district round of the season in Noakhali region.",
    //   image: "/events/noakhali-upcoming.jpg",
    //   buttonText: "Save the Date",
    //   buttonLink: "#",
    //   status: "upcoming",
    //   category: "District Round",
    //   participants: "Expected: 480+",
    //   highlights: ["Coastal science", "Final round season", "Special awards"],
    // },
  ],
};

export const eventStats: EventStat[] = [
  { value: 15, label: "Total Events" },
  { value: 50000, label: "Total Participants" },
  { value: 12, label: "Districts Covered" },
  { value: 8, label: "Upcoming Events" },
];
